"""
Knowledge Repository: manages episodic memory, canonical documents, research claims,
artifacts, digests, and user preferences.
Stored in data/knowledge.sqlite with synchronous=NORMAL and WAL journal mode.
"""

import json
import logging
import sqlite3
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

try:
    from ..connections import get_knowledge_db
    from .base import BaseRepository
except ImportError:
    from backend.db.connections import get_knowledge_db
    from backend.db.repositories.base import BaseRepository

logger = logging.getLogger(__name__)


class KnowledgeRepository(BaseRepository):
    """Data access repository for episodic memory, canonical documents, and research claims."""

    def __init__(self, db_getter=get_knowledge_db):
        super().__init__(db_getter=db_getter, db_name="knowledge")

    # =========================================================================
    # Episodic Memory
    # =========================================================================

    def write_memory(
        self,
        task_id: str,
        agent_type: str,
        summary: Dict[str, Any],
        step_id: Optional[str] = None,
        retention_tier: str = "HOT",
        expires_at: Optional[str] = None,
        memory_id: Optional[str] = None,
    ) -> str:
        """Writes an episodic memory summary generated by an agent."""
        mid = memory_id or f"mem_{uuid.uuid4().hex[:12]}"
        now = datetime.now(timezone.utc).isoformat()
        summary_json = json.dumps(summary)

        with self.write_transaction("write_memory") as cur:
            cur.execute(
                """
                INSERT INTO episodic_memory (
                    memory_id, task_id, step_id, agent_type,
                    summary_json, retention_tier, created_at, expires_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (mid, task_id, step_id, agent_type, summary_json, retention_tier, now, expires_at),
            )
        return mid

    def read_memories_for_task(
        self,
        task_id: str,
        retention_tier: Optional[str] = None,
        limit: int = 50,
    ) -> List[Dict[str, Any]]:
        """Reads episodic memories recorded for a specific task."""
        conn = self.get_connection()
        try:
            cur = conn.cursor()
            if retention_tier:
                cur.execute(
                    """
                    SELECT * FROM episodic_memory
                    WHERE task_id = ? AND retention_tier = ?
                    ORDER BY created_at ASC
                    LIMIT ?
                    """,
                    (task_id, retention_tier, limit),
                )
            else:
                cur.execute(
                    """
                    SELECT * FROM episodic_memory
                    WHERE task_id = ?
                    ORDER BY created_at ASC
                    LIMIT ?
                    """,
                    (task_id, limit),
                )
            rows = cur.fetchall()
            results = []
            for r in rows:
                item = dict(r)
                if "summary_json" in item and item["summary_json"]:
                    try:
                        item["summary"] = json.loads(item["summary_json"])
                    except Exception:
                        item["summary"] = item["summary_json"]
                results.append(item)
            return results
        finally:
            conn.close()

    def prune_expired_memories(self) -> int:
        """Deletes memories whose expires_at is in the past."""
        now = datetime.now(timezone.utc).isoformat()
        with self.write_transaction("prune_expired_memories") as cur:
            cur.execute(
                "DELETE FROM episodic_memory WHERE expires_at IS NOT NULL AND expires_at < ?",
                (now,),
            )
            return cur.rowcount

    # =========================================================================
    # Canonical Documents
    # =========================================================================

    def upsert_document(
        self,
        source_uri: str,
        domain: str,
        authority_level: str,
        title: str,
        raw_content: str,
        document_hash: str,
        embedding_config_hash: str = "nomic-v1.5",
        document_id: Optional[str] = None,
        index_status: str = "INDEXED",
    ) -> str:
        """Upserts a canonical document in the knowledge store."""
        doc_id = document_id or f"doc_{uuid.uuid4().hex[:12]}"
        now = datetime.now(timezone.utc).isoformat()

        with self.write_transaction("upsert_document") as cur:
            cur.execute(
                """
                INSERT INTO canonical_documents (
                    document_id, source_uri, domain, authority_level, title,
                    raw_content, document_hash, embedding_config_hash, valid_from, index_status
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(document_id) DO UPDATE SET
                    raw_content = excluded.raw_content,
                    document_hash = excluded.document_hash,
                    index_status = excluded.index_status,
                    valid_from = excluded.valid_from
                """,
                (
                    doc_id,
                    source_uri,
                    domain,
                    authority_level,
                    title,
                    raw_content,
                    document_hash,
                    embedding_config_hash,
                    now,
                    index_status,
                ),
            )
        return doc_id

    def get_document_by_id(self, document_id: str) -> Optional[Dict[str, Any]]:
        """Retrieves a document by document_id."""
        conn = self.get_connection()
        try:
            cur = conn.cursor()
            cur.execute("SELECT * FROM canonical_documents WHERE document_id = ?", (document_id,))
            return self.row_to_dict(cur.fetchone())
        finally:
            conn.close()

    def get_document_by_uri(self, source_uri: str) -> Optional[Dict[str, Any]]:
        """Retrieves a document by source_uri."""
        conn = self.get_connection()
        try:
            cur = conn.cursor()
            cur.execute(
                "SELECT * FROM canonical_documents WHERE source_uri = ? ORDER BY created_at DESC LIMIT 1",
                (source_uri,),
            )
            return self.row_to_dict(cur.fetchone())
        finally:
            conn.close()

    # =========================================================================
    # Research Claims
    # =========================================================================

    def save_claim(
        self,
        task_id: str,
        claim_text: str,
        source_uri: Optional[str] = None,
        source_authority: str = "UNVERIFIED",
        retrieval_timestamp: Optional[str] = None,
        confidence_score: float = 0.75,
        confidence_basis: str = "Extracted from research source",
        domain: str = "OTHER",
        claim_id: Optional[str] = None,
        evidence_count: int = 1,
        contradiction_status: str = "NONE",
    ) -> str:
        """Saves a factual claim extracted by research agents."""
        cid = claim_id or f"claim_{uuid.uuid4().hex[:12]}"
        now = retrieval_timestamp or datetime.now(timezone.utc).isoformat()

        with self.write_transaction("save_claim") as cur:
            cur.execute(
                """
                INSERT INTO research_claims (
                    claim_id, task_id, claim_text, source_uri, source_authority,
                    retrieval_timestamp, confidence_score, confidence_basis,
                    evidence_count, contradiction_status, domain
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    cid,
                    task_id,
                    claim_text[:500],
                    source_uri,
                    source_authority,
                    now,
                    confidence_score,
                    confidence_basis,
                    evidence_count,
                    contradiction_status,
                    domain,
                ),
            )
        return cid

    def get_claims_for_task(self, task_id: str) -> List[Dict[str, Any]]:
        """Retrieves all claims saved for a task."""
        conn = self.get_connection()
        try:
            cur = conn.cursor()
            cur.execute(
                "SELECT * FROM research_claims WHERE task_id = ? ORDER BY confidence_score DESC",
                (task_id,),
            )
            return self.rows_to_dicts(cur.fetchall())
        finally:
            conn.close()

    # =========================================================================
    # Digests
    # =========================================================================

    def save_digest(
        self,
        task_id: str,
        domain: str,
        title: str,
        content: str,
        sources: Optional[List[str]] = None,
        digest_id: Optional[str] = None,
    ) -> str:
        """Saves a generated topic digest."""
        did = digest_id or str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()
        sources_json = json.dumps(sources) if sources is not None else None

        with self.write_transaction("save_digest") as cur:
            cur.execute(
                """
                INSERT INTO digests (digest_id, task_id, domain, title, content, sources, generated_at, is_read)
                VALUES (?, ?, ?, ?, ?, ?, ?, 0)
                """,
                (did, task_id, domain, title, content, sources_json, now),
            )
        return did

    def list_digests(self, domain: Optional[str] = None, limit: int = 20) -> List[Dict[str, Any]]:
        """Lists recent digests optionally filtered by domain."""
        conn = self.get_connection()
        try:
            cur = conn.cursor()
            if domain:
                cur.execute(
                    "SELECT * FROM digests WHERE domain = ? ORDER BY generated_at DESC LIMIT ?",
                    (domain, limit),
                )
            else:
                cur.execute(
                    "SELECT * FROM digests ORDER BY generated_at DESC LIMIT ?",
                    (limit,),
                )
            return self.rows_to_dicts(cur.fetchall())
        finally:
            conn.close()

    # =========================================================================
    # Artifacts
    # =========================================================================

    def save_artifact_metadata(
        self,
        task_id: str,
        artifact_type: str,
        storage_path: str,
        content_hash: str,
        size_bytes: int,
        metadata: Dict[str, Any],
        step_id: Optional[str] = None,
        artifact_id: Optional[str] = None,
    ) -> str:
        """Records metadata for a durable file artifact stored on disk."""
        aid = artifact_id or f"art_{uuid.uuid4().hex[:12]}"
        now = datetime.now(timezone.utc).isoformat()
        meta_json = json.dumps(metadata)

        with self.write_transaction("save_artifact_metadata") as cur:
            cur.execute(
                """
                INSERT INTO artifacts (
                    artifact_id, task_id, step_id, artifact_type,
                    storage_path, content_hash, size_bytes, metadata_json, created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    aid,
                    task_id,
                    step_id,
                    artifact_type,
                    storage_path,
                    content_hash,
                    size_bytes,
                    meta_json,
                    now,
                ),
            )
        return aid

    def get_artifacts_for_task(self, task_id: str) -> List[Dict[str, Any]]:
        """Retrieves artifacts associated with a task."""
        conn = self.get_connection()
        try:
            cur = conn.cursor()
            cur.execute(
                "SELECT * FROM artifacts WHERE task_id = ? ORDER BY created_at ASC",
                (task_id,),
            )
            return self.rows_to_dicts(cur.fetchall())
        finally:
            conn.close()
