"""
Project Scaffolder Engine for CUA-Sentinel.

Writes only deterministic config files (package.json, tsconfig, vite.config,
.gitignore, index.html, requirements.txt) plus clean minimal entry-point stubs.
Domain-specific implementation is generated by the queued LLM task (CodeRefactorAgent.run).
"""

import os
import json
import logging
from typing import Dict, Any, List
from core.path_security import path_security
from core.ui_ux_pro_max import ui_ux_pro_max

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Domain-aware dependency detection
# ---------------------------------------------------------------------------

DOMAIN_DEPS: Dict[str, List[str]] = {
    "auth":       ["python-jose[cryptography]>=3.3.0", "passlib[bcrypt]>=1.7.4"],
    "login":      ["python-jose[cryptography]>=3.3.0", "passlib[bcrypt]>=1.7.4"],
    "jwt":        ["python-jose[cryptography]>=3.3.0", "passlib[bcrypt]>=1.7.4"],
    "oauth":      ["authlib>=1.2.0", "httpx>=0.24.0"],
    "database":   ["sqlalchemy>=2.0.0", "alembic>=1.11.0"],
    "sqlite":     ["sqlalchemy>=2.0.0"],
    "postgres":   ["sqlalchemy>=2.0.0", "psycopg2-binary>=2.9.0", "alembic>=1.11.0"],
    "sql":        ["sqlalchemy>=2.0.0", "alembic>=1.11.0"],
    "orm":        ["sqlalchemy>=2.0.0"],
    "migration":  ["alembic>=1.11.0"],
    "websocket":  ["websockets>=11.0"],
    "realtime":   ["websockets>=11.0"],
    "stream":     ["websockets>=11.0"],
    "email":      ["fastapi-mail>=1.3.0"],
    "smtp":       ["fastapi-mail>=1.3.0"],
    "image":      ["Pillow>=10.0.0"],
    "upload":     ["python-multipart>=0.0.6"],
    "file":       ["python-multipart>=0.0.6"],
    "http":       ["httpx>=0.24.0"],
    "scrape":     ["httpx>=0.24.0", "beautifulsoup4>=4.12.0"],
    "schedule":   ["apscheduler>=3.10.0"],
    "cron":       ["apscheduler>=3.10.0"],
    "redis":      ["redis>=4.6.0"],
    "cache":      ["redis>=4.6.0"],
    "csv":        ["pandas>=2.0.0"],
    "excel":      ["pandas>=2.0.0", "openpyxl>=3.1.0"],
    "ml":         ["scikit-learn>=1.3.0", "numpy>=1.24.0"],
    "numpy":      ["numpy>=1.24.0"],
    "test":       ["pytest-asyncio>=0.21.0", "httpx>=0.24.0"],
}

BASE_DEPS = [
    "fastapi>=0.100.0",
    "uvicorn[standard]>=0.22.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "pytest>=7.4.0",
]


class ProjectScaffolder:

    def _build_domain_requirements(self, description: str, tech_stack: str) -> List[str]:
        """
        Parses description + tech_stack keywords and returns a deduplicated
        pip requirements list with the right domain-specific packages.
        """
        text = (description + " " + tech_stack).lower()
        collected: Dict[str, str] = {}

        for keyword, deps in DOMAIN_DEPS.items():
            if keyword in text:
                for dep in deps:
                    pkg_name = dep.split("[")[0].split(">=")[0].split("==")[0].strip().lower()
                    if pkg_name not in collected:
                        collected[pkg_name] = dep

        all_deps = list(BASE_DEPS)
        for dep in collected.values():
            pkg_name = dep.split("[")[0].split(">=")[0].split("==")[0].strip().lower()
            if not any(pkg_name in base.lower() for base in BASE_DEPS):
                all_deps.append(dep)

        return all_deps

    def _build_package_json(self, project_name: str, description: str, blueprint_content: str = "") -> dict:
        text = (description + " " + blueprint_content).lower()
        extra: Dict[str, str] = {}

        # Charts & Data Visualization
        if any(k in text for k in ["chart", "graph", "plot", "visualization", "analytics", "kpi", "metric"]):
            extra["recharts"] = "^2.8.0"
        # Data Tables & Grids
        if any(k in text for k in ["table", "grid", "data grid", "datagrid", "records", "crud"]):
            extra["@tanstack/react-table"] = "^8.10.0"
        # Server State & Caching
        if any(k in text for k in ["query", "cache", "server state", "react query"]):
            extra["@tanstack/react-query"] = "^5.0.0"
        # Authentication
        if any(k in text for k in ["auth", "login", "jwt", "oauth", "session", "user auth"]):
            extra["jwt-decode"] = "^4.0.0"
        # Date & Time
        if any(k in text for k in ["date", "calendar", "time", "datetime", "picker", "schedule"]):
            extra["date-fns"] = "^3.6.0"
        # Forms & Validation
        if any(k in text for k in ["form", "validation", "input", "wizard", "onboarding", "zod"]):
            extra["react-hook-form"] = "^7.53.0"
            extra["zod"] = "^3.23.0"
        # Drag & Drop (Kanban, reorder)
        if any(k in text for k in ["drag", "drop", "kanban", "reorder", "dnd", "sortable"]):
            extra["@dnd-kit/core"] = "^6.1.0"
            extra["@dnd-kit/sortable"] = "^8.0.0"
        # Rich Text / Markdown Editor
        if any(k in text for k in ["editor", "rich text", "markdown", "wysiwyg", "prose"]):
            extra["@monaco-editor/react"] = "^4.6.0"
        # Maps
        if any(k in text for k in ["map", "leaflet", "geo", "location", "coordinates"]):
            extra["leaflet"] = "^1.9.4"
            extra["react-leaflet"] = "^4.2.1"
        # Notifications / Toasts
        if any(k in text for k in ["toast", "notification", "alert", "snackbar"]):
            extra["react-hot-toast"] = "^2.4.1"
        # State Management
        if any(k in text for k in ["zustand", "global state", "state management", "store"]):
            extra["zustand"] = "^4.5.0"
        # Animations
        if any(k in text for k in ["animation", "motion", "transition", "framer"]):
            extra["framer-motion"] = "^11.0.0"
        # PDF / Export
        if any(k in text for k in ["pdf", "export", "download", "print"]):
            extra["jspdf"] = "^2.5.1"
        # WebSockets / Realtime
        if any(k in text for k in ["websocket", "realtime", "socket", "live", "stream"]):
            extra["socket.io-client"] = "^4.7.0"
        # QR Code
        if any(k in text for k in ["qr", "qrcode", "barcode"]):
            extra["qrcode.react"] = "^4.0.0"
        # Image handling / Cropping
        if any(k in text for k in ["image crop", "avatar", "photo upload", "crop"]):
            extra["react-image-crop"] = "^11.0.6"

        return {
            "name": project_name.lower().replace(" ", "-"),
            "version": "1.0.0",
            "type": "module",
            "private": True,
            "scripts": {
                "dev": "vite",
                "build": "tsc && vite build",
                "lint": "eslint src --ext ts,tsx",
                "preview": "vite preview",
            },
            "dependencies": {
                "react": "^18.3.1",
                "react-dom": "^18.3.1",
                "lucide-react": "^0.447.0",
                "axios": "^1.7.7",
                **extra,
            },
            "devDependencies": {
                "@vitejs/plugin-react": "^4.3.2",
                "@types/react": "^18.3.11",
                "@types/react-dom": "^18.3.1",
                "typescript": "^5.2.2",
                "vite": "^5.4.8",
            },
        }

    def _parse_blueprint_overrides(self, blueprint_content: str, ui_style: str) -> Dict[str, Any]:
        """
        Calls UIUXProMaxEngine.parse_blueprint_style_overrides() to extract
        any explicit UI/style declarations from the user's blueprint spec.
        """
        try:
            overrides = ui_ux_pro_max.parse_blueprint_style_overrides(blueprint_content, ui_style)
            return overrides
        except Exception as e:
            logger.warning(f"Blueprint style override parsing failed: {e}")
            return {
                'detected_theme': ui_style,
                'overrides_applied': [],
                'layout_hints': {},
                'framework_hints': {},
            }

    def _build_app_tsx_stub(self, project_name: str, description: str, layout_hints: Dict[str, Any], blueprint_overrides: Dict[str, Any]) -> str:
        """
        Generates a structured App.tsx scaffold stub based on detected layout hints
        from the blueprint spec.
        """
        is_dashboard = layout_hints.get('is_dashboard', False)
        has_sidebar = layout_hints.get('has_sidebar', False) or is_dashboard
        no_sidebar = layout_hints.get('no_sidebar', False)
        is_landing = layout_hints.get('is_landing', False)
        is_form_heavy = layout_hints.get('is_form_heavy', False)
        has_table = layout_hints.get('has_table', False)
        has_kanban = layout_hints.get('has_kanban', False)
        is_chat = layout_hints.get('is_chat', False)

        header = (
            "import React, { useState } from 'react'\n"
            "import './index.css'\n\n"
            f"// {project_name} — scaffold generated by CUA-Sentinel\n"
            f"// Blueprint: {description[:120]}\n\n"
        )

        if is_chat:
            return header + (
                "export default function App() {\n"
                "  const [messages, setMessages] = useState<{role: string; text: string}[]>([])\n"
                "  const [input, setInput] = useState('')\n\n"
                "  return (\n"
                "    <div className='app-shell'>\n"
                "      <aside className='sidebar'>\n"
                f"        <div className='sidebar-header'><strong>{project_name}</strong></div>\n"
                "        <nav className='sidebar-nav'>\n"
                "          {/* Conversation list rendered here */}\n"
                "        </nav>\n"
                "      </aside>\n"
                "      <main className='main-content'>\n"
                "        <header className='header'>\n"
                f"          <span className='card-title'>{project_name}</span>\n"
                "        </header>\n"
                "        <div className='workspace-area custom-scrollbar'>\n"
                "          <div className='card' style={{flex: 1, display: 'flex', flexDirection: 'column', minHeight: '60vh'}}>\n"
                "            {/* Message list */}\n"
                "            <div style={{flex: 1}}>{messages.map((m, i) => <div key={i}><strong>{m.role}:</strong> {m.text}</div>)}</div>\n"
                "            {/* Input bar */}\n"
                "            <div className='flex gap-2' style={{marginTop: '1rem'}}>\n"
                "              <input className='input-field' value={input} onChange={e => setInput(e.target.value)} placeholder='Type a message...' />\n"
                "              <button className='btn btn-primary'>Send</button>\n"
                "            </div>\n"
                "          </div>\n"
                "        </div>\n"
                "      </main>\n"
                "    </div>\n"
                "  )\n"
                "}\n"
            )

        if has_kanban:
            return header + (
                "export default function App() {\n"
                "  const [columns] = useState([\n"
                "    { id: 'todo', title: 'To Do', cards: [] },\n"
                "    { id: 'in_progress', title: 'In Progress', cards: [] },\n"
                "    { id: 'done', title: 'Done', cards: [] },\n"
                "  ])\n\n"
                "  return (\n"
                "    <div className='app-shell'>\n"
                "      <aside className='sidebar'>\n"
                f"        <div className='sidebar-header'><strong>{project_name}</strong></div>\n"
                "        <nav className='sidebar-nav'>{/* Board navigation */}</nav>\n"
                "      </aside>\n"
                "      <main className='main-content'>\n"
                "        <header className='header'>\n"
                f"          <h1 className='card-title'>{project_name}</h1>\n"
                "        </header>\n"
                "        <div className='workspace-area custom-scrollbar'>\n"
                "          <div style={{display: 'flex', gap: '1.25rem', height: '100%'}}>\n"
                "            {columns.map(col => (\n"
                "              <div key={col.id} className='card' style={{minWidth: 280, flex: 1}}>\n"
                "                <div className='card-header'><span className='card-title'>{col.title}</span></div>\n"
                "                <div className='card-body'>{/* Cards rendered here */}</div>\n"
                "              </div>\n"
                "            ))}\n"
                "          </div>\n"
                "        </div>\n"
                "      </main>\n"
                "    </div>\n"
                "  )\n"
                "}\n"
            )

        if is_landing:
            return header + (
                "export default function App() {\n"
                "  return (\n"
                "    <div style={{background: 'var(--bg-color)', color: 'var(--text-main)', minHeight: '100vh'}}>\n"
                "      {/* Hero Section */}\n"
                "      <section style={{padding: '6rem 2rem', textAlign: 'center', maxWidth: '900px', margin: '0 auto'}}>\n"
                f"        <h1 style={{{{color: 'var(--primary-color)', fontSize: '3rem', marginBottom: '1rem'}}}}>{project_name}</h1>\n"
                f"        <p style={{{{fontSize: '1.2rem', color: 'var(--text-muted)', marginBottom: '2rem'}}}}>{description}</p>\n"
                "        <div style={{display: 'flex', gap: '1rem', justifyContent: 'center'}}>\n"
                "          <button className='btn btn-primary'>Get Started</button>\n"
                "          <button className='btn btn-secondary'>Learn More</button>\n"
                "        </div>\n"
                "      </section>\n"
                "      {/* Features Section */}\n"
                "      <section style={{padding: '4rem 2rem', maxWidth: '1100px', margin: '0 auto'}}>\n"
                "        <div className='grid-3'>{/* Feature cards rendered here */}</div>\n"
                "      </section>\n"
                "    </div>\n"
                "  )\n"
                "}\n"
            )

        if is_form_heavy:
            return header + (
                "export default function App() {\n"
                "  const [step, setStep] = useState(0)\n\n"
                "  return (\n"
                "    <div style={{display: 'flex', minHeight: '100vh', alignItems: 'center', justifyContent: 'center', background: 'var(--bg-color)'}}>\n"
                "      <div className='card' style={{width: '100%', maxWidth: '480px'}}>\n"
                "        <div className='card-header'>\n"
                f"          <span className='card-title'>{project_name}</span>\n"
                "          <span className='badge badge-info'>Step {{step + 1}}</span>\n"
                "        </div>\n"
                "        <div className='card-body'>\n"
                "          {/* Form steps rendered here */}\n"
                "          <button className='btn btn-primary' style={{marginTop: '1rem', width: '100%'}} onClick={() => setStep(s => s + 1)}>Continue</button>\n"
                "        </div>\n"
                "      </div>\n"
                "    </div>\n"
                "  )\n"
                "}\n"
            )

        if (has_sidebar and not no_sidebar) or (not is_chat and not has_kanban and not is_landing and not is_form_heavy):
            return (
                "import React, { useState, useEffect } from 'react'\n"
                "import { Server, Database, Zap, Activity } from 'lucide-react'\n"
                "import './index.css'\n"
                "import Navbar from './components/layout/Navbar'\n"
                "import Sidebar from './components/layout/Sidebar'\n"
                "import Card from './components/common/Card'\n"
                "import StatCard from './components/common/StatCard'\n"
                "import api from './api'\n\n"
                f"// {project_name} — modular scaffold generated by CUA-Sentinel\n\n"
                "export default function App() {\n"
                "  const [activeTab, setActiveTab] = useState('dashboard')\n"
                "  const [apiConnected, setApiConnected] = useState(false)\n"
                "  const [items, setItems] = useState<any[]>([])\n\n"
                "  useEffect(() => {\n"
                "    api.get('/status')\n"
                "      .then(() => setApiConnected(true))\n"
                "      .catch(() => setApiConnected(false))\n\n"
                "    api.get('/items')\n"
                "      .then(res => setItems(res.data || []))\n"
                "      .catch(() => {})\n"
                "  }, [])\n\n"
                "  return (\n"
                "    <div className='app-shell'>\n"
                f"      <Sidebar projectName='{project_name}' activeTab={{activeTab}} onSelectTab={{setActiveTab}} />\n"
                "      <main className='main-content'>\n"
                f"        <Navbar title='{project_name}' subtitle='{description[:80]}' backendOnline={{apiConnected}} />\n"
                "        <div className='workspace-area custom-scrollbar'>\n"
                "          <div className='grid-3' style={{ marginBottom: '1.25rem' }}>\n"
                "            <StatCard title='Backend Status' value={apiConnected ? 'Online' : 'Connecting'} change='FastAPI /api' isPositive={apiConnected} icon={Server} />\n"
                "            <StatCard title='Active Records' value={items.length} change='SQLite / Storage' isPositive={true} icon={Database} />\n"
                "            <StatCard title='Architecture' value='Modular V2' change='100% Type Safe' isPositive={true} icon={Zap} />\n"
                "          </div>\n\n"
                "          <Card title='Service Telemetry & Records' subtitle='Live items loaded from FastAPI backend'>\n"
                "            <div className='table-container'>\n"
                "              <table className='table'>\n"
                "                <thead>\n"
                "                  <tr>\n"
                "                    <th>ID</th>\n"
                "                    <th>Name</th>\n"
                "                    <th>Description</th>\n"
                "                    <th>Status</th>\n"
                "                  </tr>\n"
                "                </thead>\n"
                "                <tbody>\n"
                "                  {items.map((item: any) => (\n"
                "                    <tr key={item.id}>\n"
                "                      <td>#{item.id}</td>\n"
                "                      <td><strong>{item.name}</strong></td>\n"
                "                      <td>{item.description}</td>\n"
                "                      <td><span className='badge badge-success'>{item.status}</span></td>\n"
                "                    </tr>\n"
                "                  ))}\n"
                "                </tbody>\n"
                "              </table>\n"
                "            </div>\n"
                "          </Card>\n"
                "        </div>\n"
                "      </main>\n"
                "    </div>\n"
                "  )\n"
                "}\n"
            )

        return (
            header +
            "export default function App() {\n"
            "  return (\n"
            "    <div style={{padding: '2rem', fontFamily: 'var(--font-body)', background: 'var(--bg-color)', color: 'var(--text-main)', minHeight: '100vh'}}>\n"
            f"      <h1 style={{{{color: 'var(--primary-color)'}}}}>{project_name}</h1>\n"
            f"      <p style={{{{color: 'var(--text-muted)'}}}}>{description}</p>\n"
            "    </div>\n"
            "  )\n"
            "}\n"
        )

    def create_project_structure(
        self,
        project_name: str,
        target_path: str,
        tech_stack: str = "FastAPI + React",
        ui_style: str = "Glassmorphism",
        description: str = "",
        blueprint_content: str = "",
        blueprint_filename: str = "",
        backend_port: int = 8001,
        frontend_port: int = 5174,
    ) -> Dict[str, Any]:
        """
        Scaffolds config files and minimal entry-point stubs with pre-assigned ports.
        Real implementation code is generated by the queued LLM task.
        """
        path_security.validate_write_permission(target_path)
        os.makedirs(target_path, exist_ok=True)
        created_files = []

        # Parse blueprint spec for user-declared style overrides — these take priority over ui_style param
        blueprint_overrides = {}
        effective_ui_style = ui_style
        layout_hints = {}
        if blueprint_content and blueprint_content.strip():
            blueprint_overrides = self._parse_blueprint_overrides(blueprint_content, ui_style)
            detected_theme = blueprint_overrides.get('detected_theme', ui_style)
            if detected_theme != ui_style:
                logger.info(f"ProjectScaffolder: Blueprint override — ui_style '{ui_style}' -> '{detected_theme}' (from spec)")
                effective_ui_style = detected_theme
            layout_hints = blueprint_overrides.get('layout_hints', {})
            overrides_applied = blueprint_overrides.get('overrides_applied', [])
            if overrides_applied:
                logger.info(f"ProjectScaffolder: Blueprint color overrides applied: {overrides_applied}")

        # Blueprint doc
        if blueprint_content and blueprint_content.strip():
            spec_path = os.path.join(target_path, "ARCHITECTURE_SPEC.md")
            with open(spec_path, "w", encoding="utf-8") as f:
                f.write(
                    f"# Architectural Spec Blueprint: {blueprint_filename or 'Directive Spec'}\n\n"
                    f"> Custom blueprint uploaded by user.\n\n{blueprint_content}"
                )
            created_files.append("ARCHITECTURE_SPEC.md")

        css_tokens = ui_ux_pro_max.generate_css_variables(effective_ui_style)

        # README
        with open(os.path.join(target_path, "README.md"), "w", encoding="utf-8") as f:
            f.write(
                f"# {project_name}\n\n"
                f"> {description or 'Generated by CUA-Sentinel AI Developer Engine.'}\n\n"
                f"## Stack\n- **Backend:** FastAPI (Python, Port {backend_port})\n- **Frontend:** React + TypeScript + Vite (Port {frontend_port})\n"
                f"- **UI Style:** {effective_ui_style}\n\n"
                f"## Getting Started\n```bash\n# Backend\npip install -r requirements.txt\n"
                f"python backend/main.py\n\n# Frontend\nnpm install\nnpm run dev\n```\n"
            )
        created_files.append("README.md")

        # requirements.txt — domain-aware
        req_deps = self._build_domain_requirements(description, tech_stack)
        with open(os.path.join(target_path, "requirements.txt"), "w", encoding="utf-8") as f:
            f.write("\n".join(req_deps) + "\n")
        created_files.append("requirements.txt")

        # package.json
        pkg_content = self._build_package_json(project_name, description, blueprint_content)
        with open(os.path.join(target_path, "package.json"), "w", encoding="utf-8") as f:
            f.write(json.dumps(pkg_content, indent=2))
        created_files.append("package.json")

        # vite.config.ts — with /api proxy to backend_port and server port frontend_port
        vite_config_path = os.path.join(target_path, "vite.config.ts")
        if not os.path.exists(vite_config_path):
            with open(vite_config_path, "w", encoding="utf-8") as f:
                f.write(
                    f"import {{ defineConfig }} from 'vite'\nimport react from '@vitejs/plugin-react'\n\n"
                    f"export default defineConfig({{\n  plugins: [react()],\n  server: {{\n"
                    f"    port: {frontend_port},\n    host: true,\n    proxy: {{\n"
                    f"      '/api': {{ target: 'http://localhost:{backend_port}', changeOrigin: true }}\n"
                    f"    }}\n  }}\n}})\n"
                )
            created_files.append("vite.config.ts")

        # tsconfig.json
        tsconfig_path = os.path.join(target_path, "tsconfig.json")
        if not os.path.exists(tsconfig_path):
            with open(tsconfig_path, "w", encoding="utf-8") as f:
                f.write(
                    '{\n  "compilerOptions": {\n    "target": "ES2020",\n    "useDefineForClassFields": true,\n'
                    '    "lib": ["ES2020", "DOM", "DOM.Iterable"],\n    "module": "ESNext",\n'
                    '    "skipLibCheck": true,\n    "moduleResolution": "bundler",\n'
                    '    "allowImportingTsExtensions": true,\n    "resolveJsonModule": true,\n'
                    '    "isolatedModules": true,\n    "noEmit": true,\n    "jsx": "react-jsx",\n'
                    '    "strict": false\n  },\n  "include": ["src"]\n}\n'
                )
            created_files.append("tsconfig.json")

        # .gitignore
        with open(os.path.join(target_path, ".gitignore"), "w", encoding="utf-8") as f:
            f.write(
                "node_modules/\n.venv/\nvenv/\ndist/\n__pycache__/\n*.pyc\n"
                ".env\n.sentinel_backup/\nsentinel.log\nsentinel_server.log\n*.sqlite\n"
            )
        created_files.append(".gitignore")

        # .env.example
        with open(os.path.join(target_path, ".env.example"), "w", encoding="utf-8") as f:
            f.write(
                f"# {project_name} — Environment Variables\n"
                f"PORT={backend_port}\n"
                f"VITE_PORT={frontend_port}\n"
                f"VITE_API_BASE_URL=http://localhost:{backend_port}\n"
                "DATABASE_URL=sqlite:///./app.db\n"
                "SECRET_KEY=change-me-in-production\n"
                "DEBUG=true\n"
            )
        created_files.append(".env.example")

        # .env
        with open(os.path.join(target_path, ".env"), "w", encoding="utf-8") as f:
            f.write(
                f"# {project_name} — Active Environment Variables\n"
                f"PORT={backend_port}\n"
                f"VITE_PORT={frontend_port}\n"
                f"VITE_API_BASE_URL=http://localhost:{backend_port}\n"
                "DATABASE_URL=sqlite:///./app.db\n"
                "SECRET_KEY=dev-secret-key-cua-sentinel\n"
                "DEBUG=true\n"
            )
        created_files.append(".env")

        # index.html
        with open(os.path.join(target_path, "index.html"), "w", encoding="utf-8") as f:
            f.write(
                f'<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n'
                f'    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
                f'    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 100 100\'><text y=\'.9em\' font-size=\'90\'>🚀</text></svg>" />\n'
                f'    <title>{project_name}</title>\n  </head>\n  <body>\n    <div id="root"></div>\n'
                f'    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n'
            )
        created_files.append("index.html")

        # backend/ directory structure
        backend_dir = os.path.join(target_path, "backend")
        routers_dir = os.path.join(backend_dir, "routers")
        models_dir = os.path.join(backend_dir, "models")
        services_dir = os.path.join(backend_dir, "services")
        for d in [backend_dir, routers_dir, models_dir, services_dir]:
            os.makedirs(d, exist_ok=True)

        for init_dir in [backend_dir, routers_dir, models_dir, services_dir]:
            with open(os.path.join(init_dir, "__init__.py"), "w", encoding="utf-8") as f:
                f.write("")
            created_files.append(os.path.relpath(os.path.join(init_dir, "__init__.py"), target_path).replace("\\", "/"))

        # backend/models/schemas.py — Pydantic V2 models
        schemas_py = (
            '"""\nPydantic V2 Models and Schemas for CUA-Sentinel Solution.\n"""\n\n'
            'from pydantic import BaseModel, Field\n'
            'from typing import Optional, List, Any\n\n'
            'class HealthResponse(BaseModel):\n'
            '    status: str = "ok"\n'
            '    service: str\n'
            '    backend_port: int\n\n'
            'class ItemSchema(BaseModel):\n'
            '    id: Optional[int] = None\n'
            '    name: str\n'
            '    description: Optional[str] = None\n'
            '    status: Optional[str] = "active"\n\n'
            'class ItemCreate(BaseModel):\n'
            '    name: str\n'
            '    description: Optional[str] = None\n'
            '    status: Optional[str] = "active"\n\n'
            'class AnalyticsMetric(BaseModel):\n'
            '    metric_name: str\n'
            '    metric_value: float\n'
            '    unit: str = ""\n'
        )
        with open(os.path.join(models_dir, "schemas.py"), "w", encoding="utf-8") as f:
            f.write(schemas_py)
        created_files.append("backend/models/schemas.py")

        # backend/services/data_service.py — Data & state layer
        services_py = (
            '"""\nData and Business Logic Service Layer.\n"""\n\n'
            'from typing import List, Optional\n'
            'from backend.models.schemas import ItemSchema, ItemCreate\n\n'
            'class DataService:\n'
            '    def __init__(self):\n'
            '        self._items: List[ItemSchema] = [\n'
            '            ItemSchema(id=1, name="System Gateway", description="Primary API service listening", status="active"),\n'
            '            ItemSchema(id=2, name="Telemetry Engine", description="Real-time event processing node", status="active"),\n'
            '            ItemSchema(id=3, name="Data Repository", description="Structured JSON/SQLite persistence", status="active"),\n'
            '        ]\n\n'
            '    def get_all(self) -> List[ItemSchema]:\n'
            '        return self._items\n\n'
            '    def get_by_id(self, item_id: int) -> Optional[ItemSchema]:\n'
            '        for item in self._items:\n'
            '            if item.id == item_id:\n'
            '                return item\n'
            '        return None\n\n'
            '    def create(self, payload: ItemCreate) -> ItemSchema:\n'
            '        new_id = (max([i.id for i in self._items] or [0])) + 1\n'
            '        new_item = ItemSchema(id=new_id, name=payload.name, description=payload.description, status=payload.status)\n'
            '        self._items.append(new_item)\n'
            '        return new_item\n\n'
            'data_service = DataService()\n'
        )
        with open(os.path.join(services_dir, "data_service.py"), "w", encoding="utf-8") as f:
            f.write(services_py)
        created_files.append("backend/services/data_service.py")

        # backend/routers/api_router.py — Modular router
        api_router_py = (
            '"""\nMain API Router for Modular Solution Endpoints.\n"""\n\n'
            'from fastapi import APIRouter, HTTPException\n'
            'from typing import List\n'
            'from backend.models.schemas import ItemSchema, ItemCreate, AnalyticsMetric\n'
            'from backend.services.data_service import data_service\n\n'
            'router = APIRouter(tags=["Core API"])\n\n'
            '@router.get("/status")\n'
            'def get_status():\n'
            '    return {"online": True, "items_count": len(data_service.get_all())}\n\n'
            '@router.get("/items", response_model=List[ItemSchema])\n'
            'def list_items():\n'
            '    return data_service.get_all()\n\n'
            '@router.post("/items", response_model=ItemSchema)\n'
            'def create_item(payload: ItemCreate):\n'
            '    return data_service.create(payload)\n\n'
            '@router.get("/analytics")\n'
            'def get_analytics():\n'
            '    return [\n'
            '        {"metric_name": "Active Operations", "metric_value": 42.0, "unit": "ops/sec"},\n'
            '        {"metric_name": "System Health", "metric_value": 99.1, "unit": "%"},\n'
            '        {"metric_name": "Response Latency", "metric_value": 12.4, "unit": "ms"}\n'
            '    ]\n'
        )
        with open(os.path.join(routers_dir, "api_router.py"), "w", encoding="utf-8") as f:
            f.write(api_router_py)
        created_files.append("backend/routers/api_router.py")

        # backend/main.py — clean modular FastAPI app
        main_py = (
            f'"""\n{project_name} — Backend API\n'
            f'Scaffolded by CUA-Sentinel. Uses modular router architecture.\n"""\n\n'
            f'import sys, os\n'
            f'sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))\n\n'
            f'from fastapi import FastAPI\n'
            f'from fastapi.middleware.cors import CORSMiddleware\n'
            f'from backend.routers.api_router import router as api_router\n\n'
            f'app = FastAPI(title="{project_name}", version="1.0.0")\n\n'
            f'app.add_middleware(\n'
            f'    CORSMiddleware,\n'
            f'    allow_origins=["http://localhost:5173", "http://localhost:5174", f"http://localhost:{frontend_port}", "*"],\n'
            f'    allow_credentials=True,\n'
            f'    allow_methods=["*"],\n'
            f'    allow_headers=["*"],\n'
            f')\n\n'
            f'app.include_router(api_router, prefix="/api")\n\n\n'
            f'@app.get("/")\n'
            f'def root():\n'
            f'    return {{"message": "Welcome to {project_name}", "status": "online", "backend_port": {backend_port}}}\n\n\n'
            f'@app.get("/health")\n'
            f'def health():\n'
            f'    return {{"status": "ok", "service": "{project_name}", "backend_port": {backend_port}}}\n\n\n'
            f'if __name__ == "__main__":\n'
            f'    import uvicorn\n'
            f'    uvicorn.run("backend.main:app", host="0.0.0.0", port={backend_port})\n'
        )
        with open(os.path.join(backend_dir, "main.py"), "w", encoding="utf-8") as f:
            f.write(main_py)
        created_files.append("backend/main.py")

        # src/ directories structure
        src_dir = os.path.join(target_path, "src")
        components_dir = os.path.join(src_dir, "components")
        layout_dir = os.path.join(components_dir, "layout")
        common_dir = os.path.join(components_dir, "common")
        types_dir = os.path.join(src_dir, "types")
        for d in [src_dir, components_dir, layout_dir, common_dir, types_dir]:
            os.makedirs(d, exist_ok=True)

        # src/types/index.ts
        types_ts = (
            'export interface ApiResponse<T = any> {\n'
            '  status: string\n'
            '  message?: string\n'
            '  data?: T\n'
            '  error?: string\n'
            '}\n\n'
            'export interface TelemetryMetric {\n'
            '  metric_name: string\n'
            '  metric_value: number\n'
            '  unit?: string\n'
            '}\n\n'
            'export interface SolutionItem {\n'
            '  id: number\n'
            '  name: string\n'
            '  description?: string\n'
            '  status?: string\n'
            '}\n'
        )
        with open(os.path.join(types_dir, "index.ts"), "w", encoding="utf-8") as f:
            f.write(types_ts)
        created_files.append("src/types/index.ts")

        # src/components/layout/Navbar.tsx
        navbar_tsx = (
            "import React from 'react'\n"
            "import { Activity, Sparkles } from 'lucide-react'\n\n"
            "interface NavbarProps {\n"
            "  title: string\n"
            "  subtitle?: string\n"
            "  backendOnline?: boolean\n"
            "}\n\n"
            "export const Navbar: React.FC<NavbarProps> = ({ title, subtitle, backendOnline = true }) => {\n"
            "  return (\n"
            "    <header className='header' style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>\n"
            "      <div>\n"
            "        <h1 className='card-title' style={{ margin: 0 }}>{title}</h1>\n"
            "        {subtitle && <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', margin: 0 }}>{subtitle}</p>}\n"
            "      </div>\n"
            "      <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>\n"
            "        <span className={`badge ${backendOnline ? 'badge-success' : 'badge-warning'}`} style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>\n"
            "          <Activity size={12} />\n"
            "          {backendOnline ? 'API Connected' : 'Connecting...'}\n"
            "        </span>\n"
            "        <span className='badge badge-info' style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>\n"
            "          <Sparkles size={12} /> Sentinel AI\n"
            "        </span>\n"
            "      </div>\n"
            "    </header>\n"
            "  )\n"
            "}\n\n"
            "export default Navbar\n"
        )
        with open(os.path.join(layout_dir, "Navbar.tsx"), "w", encoding="utf-8") as f:
            f.write(navbar_tsx)
        created_files.append("src/components/layout/Navbar.tsx")

        # src/components/layout/Sidebar.tsx
        sidebar_tsx = (
            "import React from 'react'\n"
            "import { LayoutDashboard, BarChart3, Layers, Settings } from 'lucide-react'\n\n"
            "interface SidebarProps {\n"
            "  projectName: string\n"
            "  activeTab: string\n"
            "  onSelectTab: (tab: string) => void\n"
            "}\n\n"
            "export const Sidebar: React.FC<SidebarProps> = ({ projectName, activeTab, onSelectTab }) => {\n"
            "  const navItems = [\n"
            "    { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },\n"
            "    { id: 'analytics', label: 'Analytics', icon: BarChart3 },\n"
            "    { id: 'features', label: 'Features', icon: Layers },\n"
            "    { id: 'settings', label: 'Settings', icon: Settings },\n"
            "  ]\n\n"
            "  return (\n"
            "    <aside className='sidebar'>\n"
            "      <div className='sidebar-header' style={{ padding: '1rem', borderBottom: '1px solid var(--border-color)' }}>\n"
            "        <strong style={{ color: 'var(--primary-color)', fontSize: '1.1rem' }}>{projectName}</strong>\n"
            "      </div>\n"
            "      <nav className='sidebar-nav' style={{ padding: '0.5rem' }}>\n"
            "        {navItems.map((item) => {\n"
            "          const Icon = item.icon\n"
            "          const isActive = activeTab === item.id\n"
            "          return (\n"
            "            <button\n"
            "              key={item.id}\n"
            "              className={`nav-item ${isActive ? 'active' : ''}`}\n"
            "              onClick={() => onSelectTab(item.id)}\n"
            "              style={{ display: 'flex', alignItems: 'center', gap: '8px', width: '100%', textAlign: 'left', marginBottom: '4px' }}\n"
            "            >\n"
            "              <Icon size={16} />\n"
            "              <span>{item.label}</span>\n"
            "            </button>\n"
            "          )\n"
            "        })}\n"
            "      </nav>\n"
            "    </aside>\n"
            "  )\n"
            "}\n\n"
            "export default Sidebar\n"
        )
        with open(os.path.join(layout_dir, "Sidebar.tsx"), "w", encoding="utf-8") as f:
            f.write(sidebar_tsx)
        created_files.append("src/components/layout/Sidebar.tsx")

        # src/components/common/Card.tsx
        card_tsx = (
            "import React from 'react'\n\n"
            "interface CardProps {\n"
            "  title?: string\n"
            "  subtitle?: string\n"
            "  action?: React.ReactNode\n"
            "  children: React.ReactNode\n"
            "  className?: string\n"
            "  style?: React.CSSProperties\n"
            "}\n\n"
            "export const Card: React.FC<CardProps> = ({ title, subtitle, action, children, className = '', style }) => {\n"
            "  return (\n"
            "    <div className={`card ${className}`} style={style}>\n"
            "      {(title || action) && (\n"
            "        <div className='card-header' style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>\n"
            "          <div>\n"
            "            {title && <h3 className='card-title' style={{ margin: 0 }}>{title}</h3>}\n"
            "            {subtitle && <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', margin: 0 }}>{subtitle}</p>}\n"
            "          </div>\n"
            "          {action && <div>{action}</div>}\n"
            "        </div>\n"
            "      )}\n"
            "      <div className='card-body'>{children}</div>\n"
            "    </div>\n"
            "  )\n"
            "}\n\n"
            "export default Card\n"
        )
        with open(os.path.join(common_dir, "Card.tsx"), "w", encoding="utf-8") as f:
            f.write(card_tsx)
        created_files.append("src/components/common/Card.tsx")

        # src/components/common/StatCard.tsx
        stat_card_tsx = (
            "import React from 'react'\n"
            "import { LucideIcon } from 'lucide-react'\n\n"
            "interface StatCardProps {\n"
            "  title: string\n"
            "  value: string | number\n"
            "  change?: string\n"
            "  isPositive?: boolean\n"
            "  icon?: LucideIcon\n"
            "}\n\n"
            "export const StatCard: React.FC<StatCardProps> = ({ title, value, change, isPositive = true, icon: Icon }) => {\n"
            "  return (\n"
            "    <div className='card stat-card' style={{ padding: '1rem', display: 'flex', alignItems: 'center', gap: '1rem' }}>\n"
            "      {Icon && (\n"
            "        <div style={{ padding: '0.75rem', borderRadius: 'var(--radius-sm, 8px)', background: 'rgba(59, 130, 246, 0.15)', color: 'var(--primary-color)' }}>\n"
            "          <Icon size={22} />\n"
            "        </div>\n"
            "      )}\n"
            "      <div style={{ flex: 1 }}>\n"
            "        <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{title}</div>\n"
            "        <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--text-main)' }}>{value}</div>\n"
            "        {change && (\n"
            "          <div style={{ fontSize: '0.7rem', color: isPositive ? 'var(--cta-color, #10b981)' : '#ef4444', marginTop: '2px' }}>\n"
            "            {change}\n"
            "          </div>\n"
            "        )}\n"
            "      </div>\n"
            "    </div>\n"
            "  )\n"
            "}\n\n"
            "export default StatCard\n"
        )
        with open(os.path.join(common_dir, "StatCard.tsx"), "w", encoding="utf-8") as f:
            f.write(stat_card_tsx)
        created_files.append("src/components/common/StatCard.tsx")

        # src/index.css
        with open(os.path.join(src_dir, "index.css"), "w", encoding="utf-8") as f:
            f.write(css_tokens)
        created_files.append("src/index.css")

        # src/main.tsx
        with open(os.path.join(src_dir, "main.tsx"), "w", encoding="utf-8") as f:
            f.write(
                "import React from 'react'\nimport ReactDOM from 'react-dom/client'\n"
                "import App from './App'\nimport './index.css'\n\n"
                "ReactDOM.createRoot(document.getElementById('root')!).render(\n"
                "  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n)\n"
            )
        created_files.append("src/main.tsx")

        # src/App.tsx — smart structural stub based on blueprint layout hints
        app_tsx = self._build_app_tsx_stub(project_name, description, layout_hints, blueprint_overrides)
        with open(os.path.join(src_dir, "App.tsx"), "w", encoding="utf-8") as f:
            f.write(app_tsx)
        created_files.append("src/App.tsx")

        # src/api.ts — axios client stub
        with open(os.path.join(src_dir, "api.ts"), "w", encoding="utf-8") as f:
            f.write(
                "import axios from 'axios'\n\n"
                "const api = axios.create({\n"
                "  baseURL: '/api',\n"
                "  headers: { 'Content-Type': 'application/json' },\n"
                "})\n\n"
                "export default api\n"
                "export { api }\n"
            )
        created_files.append("src/api.ts")

        logger.info(f"Scaffolded '{project_name}' at {target_path} — {len(created_files)} files written")

        # Provision .venv + node_modules
        env_setup_result: Dict[str, Any] = {}
        try:
            from core.environment_engine import environment_engine
            env_setup_result = environment_engine.scan_and_install_dependencies(target_path)
        except Exception as env_err:
            logger.warning(f"ProjectScaffolder: Environment provisioning notice: {env_err}")

        # Auto-register scaffolded project in database registry
        try:
            from core.projects_manager import projects_manager
            projects_manager.register_project(
                project_name=project_name,
                target_path=target_path,
                tech_stack=tech_stack,
                ui_style=ui_style,
                blueprint_filename=blueprint_filename,
                backend_port=backend_port,
                frontend_port=frontend_port
            )
            logger.info(f"ProjectScaffolder: Auto-registered project '{project_name}' in projects database")
        except Exception as reg_err:
            logger.warning(f"ProjectScaffolder: Auto-registration notice: {reg_err}")

        return {
            "project_name": project_name,
            "target_path": target_path,
            "tech_stack": tech_stack,
            "ui_style": ui_style,
            "created_files": created_files,
            "env_setup": env_setup_result,
        }


project_scaffolder = ProjectScaffolder()
