"""Deterministic Spec Compiler for Blender 3D.

Translates QuadrupedSpec, HardSurfaceSpec, and VesselSpec into a single,
self-contained, standalone bpy script that executes in headless or
interactive Blender.

Key v3 changes:
- Hex color strings → sRGB→linear conversion via srgb_to_linear().
- All offset/position fields use Vec3 (x/y/z keys).
- Unique build suffix via MD5 of spec JSON — all object/material names suffixed.
- Model objects placed in Sentinel_Model_{suffix} collection.
- Staging objects (lights, camera, floor) in Sentinel_Staging_{suffix}.
- Only the Model collection is appended to the live session.
- Skin modifier branch_smoothing = 0.5 applied for organic skeletons.
- VesselSpec compiled via bmesh.ops.spin revolution.
- Pattern solver: CORNERS / WHEEL_POSITIONS / RING / GRID.
- All relation types: ON_TOP_OF, INSET, ALIGN_CENTER, CORNER_LEGS, WHEEL_POSITIONS, RING_POSITIONS.
- No viewport shading in headless script (bpy.context.screen is None in -b mode).
  Viewport shading is handled exclusively in the live-append script.
"""

import json
import hashlib
from typing import Union
from .schema import QuadrupedSpec, HardSurfaceSpec, VesselSpec


def _build_suffix(spec_json: str) -> str:
    return hashlib.md5(spec_json.encode()).hexdigest()[:6]


class SpecCompiler:

    @classmethod
    def compile_to_script(
        cls,
        spec: Union[QuadrupedSpec, HardSurfaceSpec, VesselSpec],
        out_blend_path: str = "",
        out_metrics_path: str = "",
    ) -> str:
        """Compile spec to a self-contained, executable Blender Python script."""
        spec_json = json.dumps(spec.model_dump())
        suffix = _build_suffix(spec_json)
        model_coll = f"Sentinel_Model_{suffix}"

        header = cls._compile_header(spec_json, out_blend_path, out_metrics_path, suffix, model_coll)

        if isinstance(spec, QuadrupedSpec):
            body = cls._compile_skeleton_body()
        elif isinstance(spec, VesselSpec):
            body = cls._compile_vessel_body()
        else:
            body = cls._compile_hardsurface_body()

        footer = cls._compile_footer(model_coll)
        return header + body + footer

    # ----------------------------------------------------------------
    # Header — shared setup
    # ----------------------------------------------------------------

    @classmethod
    def _compile_header(cls, spec_json, out_blend, out_metrics, suffix, model_coll) -> str:
        return f"""# Auto-generated by CUA-Sentinel Spec3D Compiler v3
import bpy
import bmesh
import json
import math
import sys
import os
import hashlib

SPEC_DATA = json.loads({repr(spec_json)})
OUT_BLEND = {repr(out_blend)}
OUT_METRICS = {repr(out_metrics)}
BUILD_SUFFIX = {repr(suffix)}
MODEL_COLL_NAME = {repr(model_coll)}

# CLI override arguments: blender -b ... -- --out-blend <p> --out-json <p>
argv = sys.argv
if "--" in argv:
    args = argv[argv.index("--") + 1:]
    for i in range(len(args) - 1):
        if args[i] == "--out-blend":
            OUT_BLEND = args[i + 1]
        elif args[i] == "--out-json":
            OUT_METRICS = args[i + 1]

# 1. Clear default scene
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for coll in list(bpy.data.collections):
    bpy.data.collections.remove(coll)

# 2. Create dedicated model collection
model_coll = bpy.data.collections.new(MODEL_COLL_NAME)
bpy.context.scene.collection.children.link(model_coll)

created_objects = []

# ----------------------------------------------------------------
# Utility helpers
# ----------------------------------------------------------------

def srgb_to_linear(c):
    \"\"\"Convert one sRGB channel (0–1) to linear light.\"\"\"
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

def hex_to_linear_rgba(hex_str, alpha=1.0):
    \"\"\"Convert '#RRGGBB' hex string to linear-light (r, g, b, a) tuple.\"\"\"
    h = hex_str.lstrip('#')
    r_s, g_s, b_s = (int(h[i:i+2], 16) / 255.0 for i in (0, 2, 4))
    return (srgb_to_linear(r_s), srgb_to_linear(g_s), srgb_to_linear(b_s), alpha)

def make_pbr_material(name, mat_spec):
    \"\"\"Create a Principled BSDF material from a MaterialSpec dict.
    color field is expected as '#RRGGBB' hex string; falls back to list for
    backward compatibility.
    \"\"\"
    mat_name = f\"{{name}}_{{BUILD_SUFFIX}}\"
    mat = bpy.data.materials.new(name=mat_name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    bsdf = nodes.get("Principled BSDF")
    if not bsdf:
        return mat

    color_val = mat_spec.get("color", "#CCCCCC")
    if isinstance(color_val, str) and color_val.startswith('#'):
        linear_rgba = hex_to_linear_rgba(color_val)
    elif isinstance(color_val, (list, tuple)) and len(color_val) >= 3:
        # Legacy float list — pass through
        linear_rgba = (float(color_val[0]), float(color_val[1]),
                       float(color_val[2]), float(color_val[3]) if len(color_val) > 3 else 1.0)
    else:
        linear_rgba = (0.8, 0.8, 0.8, 1.0)

    bsdf.inputs["Base Color"].default_value = linear_rgba
    bsdf.inputs["Roughness"].default_value = float(mat_spec.get("roughness", 0.5))
    bsdf.inputs["Metallic"].default_value = float(mat_spec.get("metallic", 0.0))

    # Blender 4.x socket names (with 3.x fallback)
    coat = float(mat_spec.get("coat_weight", 0.0))
    if "Coat Weight" in bsdf.inputs:
        bsdf.inputs["Coat Weight"].default_value = coat
    elif "Clearcoat" in bsdf.inputs:
        bsdf.inputs["Clearcoat"].default_value = coat

    if "Specular IOR Level" in bsdf.inputs:
        bsdf.inputs["Specular IOR Level"].default_value = 0.5
    elif "Specular" in bsdf.inputs:
        bsdf.inputs["Specular"].default_value = 0.5

    return mat

def link_to_model_coll(obj):
    \"\"\"Move object from scene root collection into the model collection.\"\"\"
    if obj.name not in model_coll.objects:
        model_coll.objects.link(obj)
    for coll in obj.users_collection:
        if coll != model_coll:
            coll.objects.unlink(obj)
    obj.name = f\"{{obj.name}}_{{BUILD_SUFFIX}}\"
    created_objects.append(obj)
    return obj

"""

    # ----------------------------------------------------------------
    # Skeleton / Skin body  (QuadrupedSpec)
    # ----------------------------------------------------------------

    @classmethod
    def _compile_skeleton_body(cls) -> str:
        return """
# ================================================================
# BUILD: Organic skeleton via Skin modifier
# ================================================================
spec = SPEC_DATA

mesh = bpy.data.meshes.new(spec.get("name", "quadruped_mesh"))
obj = bpy.data.objects.new(spec.get("name", "quadruped"), mesh)
model_coll.objects.link(obj)
bpy.context.view_layer.objects.active = obj

bm = bmesh.new()
skin_layer = bm.verts.layers.skin.verify()

vert_map = {}
for j in spec.get("joints", []):
    jx = float(j["x"])
    jname = j["name"]
    # Enforce exact centerline x=0 for non-lateral joints
    if not (jname.endswith("_L") or jname.endswith("_R")):
        jx = 0.0
    v = bm.verts.new((jx, float(j["y"]), float(j["z"])))
    v[skin_layer].radius = (float(j.get("rx", 0.05)), float(j.get("ry", 0.05)))
    vert_map[jname] = v

# Mark pelvis (or first joint) as root
root_name = "pelvis" if "pelvis" in vert_map else (list(vert_map.keys())[0] if vert_map else None)
if root_name and root_name in vert_map:
    vert_map[root_name][skin_layer].use_root = True

bm.verts.ensure_lookup_table()

for b in spec.get("bones", []):
    pname, cname = b.get("parent"), b.get("child")
    if pname in vert_map and cname in vert_map:
        try:
            bm.edges.new((vert_map[pname], vert_map[cname]))
        except ValueError:
            pass  # duplicate edge

bm.to_mesh(mesh)
bm.free()

# Modifier stack: MIRROR -> SKIN (branch_smoothing=0.5) -> SUBSURF
mod_mirror = obj.modifiers.new(name="Mirror", type='MIRROR')
mod_mirror.use_axis[0] = True
mod_mirror.use_mirror_merge = True
mod_mirror.merge_threshold = 0.002

mod_skin = obj.modifiers.new(name="Skin", type='SKIN')
mod_skin.use_x_symmetry = True
if hasattr(mod_skin, 'branch_smoothing'):
    mod_skin.branch_smoothing = 0.5

subdiv = int(spec.get("finish", {}).get("subdiv_levels", 2))
if subdiv > 0:
    mod_sub = obj.modifiers.new(name="Subdivision", type='SUBSURF')
    mod_sub.levels = subdiv
    mod_sub.render_levels = subdiv

bpy.ops.object.select_all(action='DESELECT')
obj.select_set(True)
bpy.ops.object.shade_smooth()

mat = make_pbr_material("Fur", spec.get("material", {}))
obj.data.materials.append(mat)
link_to_model_coll(obj)

# Attachments (ears, snout details, etc.)
for att in spec.get("attachments", []):
    pj_name = att.get("parent_joint")
    shape = att.get("shape", "CONE")
    # Accept both Vec3 dict and legacy list for scale/offset
    scale_raw = att.get("scale", {"x": 0.04, "y": 0.03, "z": 0.08})
    offset_raw = att.get("offset", {"x": 0.0, "y": 0.0, "z": 0.0})
    if isinstance(scale_raw, dict):
        scale = [scale_raw.get("x", 0.04), scale_raw.get("y", 0.03), scale_raw.get("z", 0.08)]
    else:
        scale = list(scale_raw)
    if isinstance(offset_raw, dict):
        offset = [offset_raw.get("x", 0.0), offset_raw.get("y", 0.0), offset_raw.get("z", 0.0)]
    else:
        offset = list(offset_raw)

    pj = next((j for j in spec.get("joints", []) if j["name"] == pj_name), None)
    if pj:
        loc = (float(pj["x"]) + offset[0], float(pj["y"]) + offset[1], float(pj["z"]) + offset[2])
        if shape == "CONE":
            bpy.ops.mesh.primitive_cone_add(radius1=scale[0], depth=scale[2], location=loc)
        elif shape == "SPHERE":
            bpy.ops.mesh.primitive_uv_sphere_add(radius=scale[0], location=loc)
        elif shape == "CYLINDER":
            bpy.ops.mesh.primitive_cylinder_add(radius=scale[0], depth=scale[2], location=loc)
        else:
            bpy.ops.mesh.primitive_cube_add(size=scale[0] * 2, location=loc)

        att_obj = bpy.context.active_object
        att_obj.name = att.get("name", "attachment")
        bpy.ops.object.shade_smooth()
        if "_L" in att.get("name", ""):
            att_mirror = att_obj.modifiers.new(name="Mirror", type='MIRROR')
            att_mirror.use_axis[0] = True
        att_obj.data.materials.append(mat)
        link_to_model_coll(att_obj)
"""

    # ----------------------------------------------------------------
    # Vessel / revolution body  (VesselSpec)
    # ----------------------------------------------------------------

    @classmethod
    def _compile_vessel_body(cls) -> str:
        return """
# ================================================================
# BUILD: Profile revolution (bmesh.ops.spin)
# ================================================================
import mathutils

spec = SPEC_DATA
profile_pts = spec.get("profile", [])
steps = int(spec.get("steps", 32))
wall_thickness = float(spec.get("wall_thickness", 0.005))
bottom_closed = bool(spec.get("bottom_closed", True))

mesh = bpy.data.meshes.new(spec.get("name", "vessel_mesh"))
vessel_obj = bpy.data.objects.new(spec.get("name", "vessel"), mesh)
model_coll.objects.link(vessel_obj)
bpy.context.view_layer.objects.active = vessel_obj

bm = bmesh.new()

# Build profile edge chain in the XZ plane (radius = X, height = Z)
profile_verts = []
for pt in profile_pts:
    r = float(pt.get("radius", 0.0))
    h = float(pt.get("height", 0.0))
    v = bm.verts.new((r, 0.0, h))
    profile_verts.append(v)

bm.verts.ensure_lookup_table()
profile_edges = []
for i in range(len(profile_verts) - 1):
    e = bm.edges.new((profile_verts[i], profile_verts[i + 1]))
    profile_edges.append(e)

# Spin 360° around Z axis
geom = list(profile_verts) + list(profile_edges)
spin_result = bmesh.ops.spin(
    bm,
    geom=geom,
    cent=(0.0, 0.0, 0.0),
    axis=(0.0, 0.0, 1.0),
    angle=math.tau,
    steps=steps,
    use_duplicate=False,
)

# Weld the seam edge loop — use 1mm tolerance to catch FP drift from spin
bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=0.001)
bmesh.ops.recalc_face_normals(bm, faces=bm.faces)

# Fill bottom cap
if bottom_closed:
    bottom_verts = [v for v in bm.verts if abs(v.co.z - float(profile_pts[0].get("height", 0.0))) < 0.0005]
    if bottom_verts:
        try:
            bmesh.ops.convex_hull(bm, input=bottom_verts)
        except Exception:
            pass

bm.to_mesh(mesh)
bm.free()

# SOLIDIFY for wall thickness
mod_solid = vessel_obj.modifiers.new(name="Solidify", type='SOLIDIFY')
mod_solid.thickness = wall_thickness
mod_solid.offset = -1.0  # Inward offset gives inner wall

# Finish
finish_spec = spec.get("finish", {})
subdiv = int(finish_spec.get("subdiv_levels", 2))
if subdiv > 0:
    mod_sub = vessel_obj.modifiers.new(name="Subdivision", type='SUBSURF')
    mod_sub.levels = subdiv
    mod_sub.render_levels = subdiv

bpy.ops.object.select_all(action='DESELECT')
vessel_obj.select_set(True)
bpy.ops.object.shade_smooth()

mat = make_pbr_material("VesselMat", spec.get("material", {}))
vessel_obj.data.materials.append(mat)
link_to_model_coll(vessel_obj)

# Optional torus handle
handle_spec = spec.get("handle")
if handle_spec:
    major_r = float(handle_spec.get("major_radius", 0.028))
    minor_r = float(handle_spec.get("minor_radius", 0.006))
    off_x = float(handle_spec.get("offset_x", 0.0))
    off_z = float(handle_spec.get("offset_z", 0.05))

    # Position handle at the side of the vessel, offset outward
    profile_max_r = max(float(pt.get("radius", 0.0)) for pt in profile_pts)
    handle_x = profile_max_r + off_x
    bpy.ops.mesh.primitive_torus_add(
        major_radius=major_r,
        minor_radius=minor_r,
        location=(handle_x, 0.0, off_z),
        rotation=(0.0, math.pi / 2, 0.0)
    )
    h_obj = bpy.context.active_object
    h_obj.name = "handle"
    bpy.ops.object.shade_smooth()
    h_mat_spec = handle_spec.get("material") or spec.get("material", {})
    h_mat = make_pbr_material("HandleMat", h_mat_spec)
    h_obj.data.materials.append(h_mat)
    link_to_model_coll(h_obj)
"""

    # ----------------------------------------------------------------
    # Hard-surface body  (HardSurfaceSpec)
    # ----------------------------------------------------------------

    @classmethod
    def _compile_hardsurface_body(cls) -> str:
        return """
# ================================================================
# BUILD: Hard-surface parts + pattern solver
# ================================================================
import mathutils
spec = SPEC_DATA
parts_by_name = {}
part_specs_by_name = {p["name"]: p for p in spec.get("parts", [])}

def resolve_offset(offset_raw):
    \"\"\"Accept Vec3 dict or legacy list.\"\"\"
    if isinstance(offset_raw, dict):
        return (float(offset_raw.get("x", 0.0)),
                float(offset_raw.get("y", 0.0)),
                float(offset_raw.get("z", 0.0)))
    if isinstance(offset_raw, (list, tuple)) and len(offset_raw) >= 3:
        return (float(offset_raw[0]), float(offset_raw[1]), float(offset_raw[2]))
    return (0.0, 0.0, 0.0)

def build_part(p, location=(0, 0, 0), name_override=None):
    pname = name_override or p["name"]
    prim = p.get("primitive", "BOX")
    size = p.get("size", [1.0, 1.0, 1.0])
    end_fill = p.get("end_fill_type", "NGON") or "NGON"

    if prim == "CYLINDER":
        r, d = float(size[0]), float(size[1])
        bpy.ops.mesh.primitive_cylinder_add(radius=r, depth=d,
                                            end_fill_type=end_fill,
                                            location=location)
    elif prim == "TORUS":
        major_r, minor_r = float(size[0]), float(size[1])
        bpy.ops.mesh.primitive_torus_add(
            major_radius=major_r, minor_radius=minor_r,
            location=location, rotation=(0, math.pi / 2, 0))
    elif prim == "SPHERE":
        bpy.ops.mesh.primitive_uv_sphere_add(radius=float(size[0]), location=location)
    elif prim == "PLANE":
        bpy.ops.mesh.primitive_plane_add(size=float(size[0]), location=location)
    else:  # BOX
        sx = float(size[0]) if len(size) > 0 else 1.0
        sy = float(size[1]) if len(size) > 1 else sx
        sz = float(size[2]) if len(size) > 2 else sx
        bpy.ops.mesh.primitive_cube_add(size=1.0, location=location)
        bpy.context.active_object.scale = (sx, sy, sz)
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

    p_obj = bpy.context.active_object
    p_obj.name = pname
    bpy.ops.object.shade_smooth()

    for m in p.get("modifiers", []):
        mtype = m.get("type")
        if mtype == "SOLIDIFY":
            mod = p_obj.modifiers.new(name="Solidify", type='SOLIDIFY')
            mod.thickness = float(m.get("thickness", 0.005))
        elif mtype == "BEVEL":
            mod = p_obj.modifiers.new(name="Bevel", type='BEVEL')
            mod.width = float(m.get("width", 0.002))
            mod.segments = int(m.get("segments", 2))
        elif mtype == "SUBSURF":
            mod = p_obj.modifiers.new(name="Subdivision", type='SUBSURF')
            lvl = int(m.get("levels", 2))
            mod.levels = lvl
            mod.render_levels = lvl
        elif mtype == "MIRROR":
            mod = p_obj.modifiers.new(name="Mirror", type='MIRROR')
            mod.use_axis[0] = True

    p_mat = make_pbr_material(p.get("material", {}).get("name", pname), p.get("material", {}))
    p_obj.data.materials.append(p_mat)
    return p_obj

# ---- Pattern solver ----

def pattern_positions(p, parent_obj=None):
    \"\"\"Return list of (x, y, z) world positions for a part's pattern.\"\"\"
    pattern = p.get("pattern", "SINGLE")
    count = int(p.get("count", 1))
    size = p.get("size", [1.0, 1.0, 1.0])

    if pattern == "SINGLE":
        return [(0.0, 0.0, 0.0)]

    if pattern == "CORNERS" and parent_obj:
        # Use parent bounding box
        bb = parent_obj.bound_box  # 8 corners in local space
        xs = [parent_obj.matrix_world @ mathutils.Vector(c) for c in bb]
        max_x = max(v.x for v in xs)
        max_y = max(v.y for v in xs)
        min_z = min(v.z for v in xs)
        inset = 0.06
        return [
            ( max_x - inset,  max_y - inset, min_z),
            (-max_x + inset,  max_y - inset, min_z),
            ( max_x - inset, -max_y + inset, min_z),
            (-max_x + inset, -max_y + inset, min_z),
        ]

    if pattern == "WHEEL_POSITIONS" and parent_obj:
        bb = parent_obj.bound_box
        xs = [parent_obj.matrix_world @ mathutils.Vector(c) for c in bb]
        max_x = max(v.x for v in xs)
        max_y = max(v.y for v in xs)
        min_z = min(v.z for v in xs)
        inset = 0.10
        fwd = max_y * 0.65
        return [
            ( max_x,  fwd, min_z),
            (-max_x,  fwd, min_z),
            ( max_x, -fwd, min_z),
            (-max_x, -fwd, min_z),
        ]

    if pattern == "RING":
        r = float(size[0]) * 1.5
        return [
            (r * math.cos(2 * math.pi * i / count),
             r * math.sin(2 * math.pi * i / count),
             0.0)
            for i in range(count)
        ]

    if pattern == "GRID":
        side = math.ceil(math.sqrt(count))
        spacing = float(size[0]) * 1.1
        positions = []
        for i in range(count):
            row, col = divmod(i, side)
            positions.append((col * spacing, row * spacing, 0.0))
        return positions

    return [(0.0, 0.0, 0.0)]

# ---- Relation resolver ----

def apply_relations(relations, parts_by_name, part_specs_by_name):
    for rel in relations:
        rtype = rel.get("relation_type")
        tgt = parts_by_name.get(rel.get("target_part"))
        parent = parts_by_name.get(rel.get("parent_part"))
        offset = resolve_offset(rel.get("offset", {}))
        inset_val = float(rel.get("inset", 0.0))

        if tgt is None or parent is None:
            continue

        depsgraph = bpy.context.evaluated_depsgraph_get()
        parent_eval = parent.evaluated_get(depsgraph)
        parent_mesh = parent_eval.to_mesh()
        parent_verts = [parent.matrix_world @ v.co for v in parent_mesh.vertices]
        parent_eval.to_mesh_clear()

        max_z = max(v.z for v in parent_verts) if parent_verts else 0.0
        min_z = min(v.z for v in parent_verts) if parent_verts else 0.0
        max_x = max(v.x for v in parent_verts) if parent_verts else 0.0
        max_y = max(v.y for v in parent_verts) if parent_verts else 0.0

        if rtype == "ON_TOP_OF":
            tgt.location = (
                parent.location.x + offset[0],
                parent.location.y + offset[1],
                max_z + offset[2],
            )

        elif rtype == "INSET":
            tgt.location = (
                parent.location.x + offset[0],
                parent.location.y + offset[1],
                parent.location.z - inset_val + offset[2],
            )

        elif rtype == "ALIGN_CENTER":
            tgt.location = (
                parent.location.x + offset[0],
                parent.location.y + offset[1],
                parent.location.z + offset[2],
            )

        elif rtype == "ATTACH_SIDE":
            tgt.location = (
                parent.location.x + max_x + offset[0],
                parent.location.y + offset[1],
                parent.location.z + offset[2],
            )

        elif rtype == "CORNER_LEGS":
            # The target part is a single prototype leg — generate 4 corner instances
            tgt_spec = part_specs_by_name.get(rel.get("target_part"), {})
            leg_size = tgt_spec.get("size", [0.025, 0.71])
            leg_r = float(leg_size[0])
            leg_h = float(leg_size[1])
            corner_positions = [
                ( max_x - inset_val,  max_y - inset_val, leg_h / 2.0),
                (-max_x + inset_val,  max_y - inset_val, leg_h / 2.0),
                ( max_x - inset_val, -max_y + inset_val, leg_h / 2.0),
                (-max_x + inset_val, -max_y + inset_val, leg_h / 2.0),
            ]
            for idx, (lx, ly, lz) in enumerate(corner_positions, start=1):
                new_leg = build_part(tgt_spec, location=(lx, ly, lz),
                                     name_override=f"{tgt_spec.get('name', 'leg')}_{idx}")
                link_to_model_coll(new_leg)
            # Remove the prototype leg from scene (it was a template)
            if tgt in created_objects:
                created_objects.remove(tgt)
            bpy.data.objects.remove(tgt, do_unlink=True)
            parts_by_name.pop(rel.get("target_part"), None)

        elif rtype in ("WHEEL_POSITIONS", "RING_POSITIONS"):
            tgt_spec = part_specs_by_name.get(rel.get("target_part"), {})
            positions = pattern_positions({"pattern": rtype.replace("_POSITIONS", ""),
                                           "count": 4,
                                           "size": tgt_spec.get("size", [0.22, 0.12])}, parent)
            for idx, (wx, wy, wz) in enumerate(positions, start=1):
                new_w = build_part(tgt_spec, location=(wx, wy, wz),
                                   name_override=f"{tgt_spec.get('name', 'wheel')}_{idx}")
                # Rotate wheels 90° around Y for proper orientation
                new_w.rotation_euler = (0.0, math.pi / 2, 0.0)
                bpy.ops.object.transform_apply(location=False, rotation=True, scale=False)
                link_to_model_coll(new_w)
            if tgt in created_objects:
                created_objects.remove(tgt)
            bpy.data.objects.remove(tgt, do_unlink=True)
            parts_by_name.pop(rel.get("target_part"), None)

# Build all parts (SINGLE pattern, no relations yet)
for p in spec.get("parts", []):
    pattern = p.get("pattern", "SINGLE")
    if pattern == "SINGLE":
        p_obj = build_part(p)
        link_to_model_coll(p_obj)
        parts_by_name[p["name"]] = p_obj
    else:
        # Multi-instance pattern: build a prototype first, then duplicate
        proto = build_part(p)
        positions = pattern_positions(p)
        for idx, pos in enumerate(positions, start=1):
            if idx == 1:
                proto.location = pos
                link_to_model_coll(proto)
                parts_by_name[p["name"]] = proto
            else:
                dup = proto.copy()
                dup.data = proto.data.copy()
                dup.name = f"{p['name']}_{idx}"
                dup.location = pos
                model_coll.objects.link(dup)
                link_to_model_coll(dup)

# Resolve relations
apply_relations(spec.get("relations", []), parts_by_name, part_specs_by_name)
"""

    # ----------------------------------------------------------------
    # Footer — ground alignment, staging, metrics, save
    # ----------------------------------------------------------------

    @classmethod
    def _compile_footer(cls, model_coll_placeholder: str) -> str:
        return """
# ================================================================
# FOOTER: Ground alignment, metrics, staging, save
# ================================================================

depsgraph = bpy.context.evaluated_depsgraph_get()
min_z = float('inf')
total_poly_count = 0

# Filter out any objects that were deleted during relation solving
created_objects = [o for o in created_objects if o and o.name in bpy.data.objects]

for obj in created_objects:
    try:
        eval_obj = obj.evaluated_get(depsgraph)
        eval_mesh = eval_obj.to_mesh()
        for v in eval_mesh.vertices:
            world_v = obj.matrix_world @ v.co
            if world_v.z < min_z:
                min_z = world_v.z
        total_poly_count += len(eval_mesh.polygons)
        eval_obj.to_mesh_clear()
    except Exception:
        pass

# Shift all model objects so lowest vertex rests at z=0
if min_z != float('inf') and min_z != 0.0:
    for obj in created_objects:
        obj.location.z -= min_z

# Staging collection (lights + camera) — separate from model
staging_coll = bpy.data.collections.new(f"Sentinel_Staging_{BUILD_SUFFIX}")
bpy.context.scene.collection.children.link(staging_coll)

# Studio key light
light_data = bpy.data.lights.new(name=f"Key_Sun_{BUILD_SUFFIX}", type='SUN')
light_data.energy = 4.0
light_obj = bpy.data.objects.new(name=f"Key_Sun_{BUILD_SUFFIX}", object_data=light_data)
staging_coll.objects.link(light_obj)
light_obj.location = (3.0, -3.0, 5.0)

# Fill light
fill_data = bpy.data.lights.new(name=f"Fill_Area_{BUILD_SUFFIX}", type='AREA')
fill_data.energy = 200.0
fill_obj = bpy.data.objects.new(name=f"Fill_Area_{BUILD_SUFFIX}", object_data=fill_data)
staging_coll.objects.link(fill_obj)
fill_obj.location = (-3.0, 2.0, 4.0)

# NOTE: NO viewport shading changes here — bpy.context.screen is None in -b mode.
# Viewport shading is handled exclusively in the live-append script.

# Export world-space geometry for software silhouette projection (runner.py)
# Kept under a size cap to avoid huge metrics files for dense meshes.
_MAX_VERTS_FOR_EXPORT = 50000
_world_verts = []
_polys = []
_export_geom = total_poly_count < 200000  # skip for pathologically dense meshes
if _export_geom:
    for _obj in created_objects:
        try:
            _eval = _obj.evaluated_get(depsgraph)
            _emesh = _eval.to_mesh()
            _offset = len(_world_verts)
            for _v in _emesh.vertices:
                _wv = _obj.matrix_world @ _v.co
                _world_verts.append([_wv.x, _wv.y, _wv.z])
            for _p in _emesh.polygons:
                _polys.append([_i + _offset for _i in _p.vertices])
            _eval.to_mesh_clear()
            if len(_world_verts) > _MAX_VERTS_FOR_EXPORT:
                break  # cap reached — partial export is fine for silhouettes
        except Exception:
            pass

# Metrics
metrics = {
    "ok": True,
    "build_suffix": BUILD_SUFFIX,
    "model_collection": MODEL_COLL_NAME,
    "object_count": len(created_objects),
    "total_polys": total_poly_count,
    "lowest_z": 0.0,
    "objects": [o.name for o in created_objects],
    "world_verts": _world_verts,
    "polys": _polys,
}

if OUT_METRICS:
    try:
        import os as _os
        _os.makedirs(_os.path.dirname(_os.path.abspath(OUT_METRICS)), exist_ok=True)
        with open(OUT_METRICS, "w", encoding="utf-8") as f:
            json.dump(metrics, f, indent=2)
    except Exception as e:
        print(f"Error saving metrics: {e}")

if OUT_BLEND:
    try:
        import os as _os
        _os.makedirs(_os.path.dirname(_os.path.abspath(OUT_BLEND)), exist_ok=True)
        bpy.ops.wm.save_as_mainfile(filepath=OUT_BLEND)
        print(f"Saved verified blend to: {OUT_BLEND}")
    except Exception as e:
        print(f"Error saving blend: {e}")

print("SENTINEL_OUTPUT_START" + json.dumps(metrics) + "SENTINEL_OUTPUT_END")
"""
